// flow-typed signature: 81ba6277396fe98d57ef6ad696e56658
// flow-typed version: <<STUB>>/@capacitor/android_v^5.3.0/flow_v0.216.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@capacitor/android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@capacitor/android' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@capacitor/android/capacitor/build/intermediates/library_assets/debug/out/native-bridge' {
  declare module.exports: any;
}

declare module '@capacitor/android/capacitor/src/main/assets/native-bridge' {
  declare module.exports: any;
}

// Filename aliases
declare module '@capacitor/android/capacitor/build/intermediates/library_assets/debug/out/native-bridge.js' {
  declare module.exports: $Exports<'@capacitor/android/capacitor/build/intermediates/library_assets/debug/out/native-bridge'>;
}
declare module '@capacitor/android/capacitor/src/main/assets/native-bridge.js' {
  declare module.exports: $Exports<'@capacitor/android/capacitor/src/main/assets/native-bridge'>;
}
