// flow-typed signature: 655b3ba2e5d92d8769785a7a01c5d9b4
// flow-typed version: <<STUB>>/@capacitor/cli_v^5.3.0/flow_v0.216.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@capacitor/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@capacitor/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@capacitor/cli/dist/android/add' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/android/build' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/android/common' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/android/doctor' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/android/open' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/android/run' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/android/update' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/colors' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/common' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/config' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/cordova' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/declarations' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/definitions' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/errors' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/framework-configs' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/ios/add' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/ios/build' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/ios/common' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/ios/doctor' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/ios/open' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/ios/run' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/ios/update' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/ipc' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/log' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/plugin' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/sysconfig' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/add' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/build' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/config' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/copy' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/create' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/doctor' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/init' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/list' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/migrate' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/new-plugin' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/open' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/run' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/serve' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/sourcemaps' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/sync' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/telemetry' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/tasks/update' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/telemetry' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/cli' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/emoji' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/fn' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/fs' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/js' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/monorepotools' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/native-run' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/node' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/promise' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/subprocess' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/template' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/term' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/uuid' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/util/xml' {
  declare module.exports: any;
}

declare module '@capacitor/cli/dist/web/copy' {
  declare module.exports: any;
}

// Filename aliases
declare module '@capacitor/cli/dist/android/add.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/android/add'>;
}
declare module '@capacitor/cli/dist/android/build.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/android/build'>;
}
declare module '@capacitor/cli/dist/android/common.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/android/common'>;
}
declare module '@capacitor/cli/dist/android/doctor.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/android/doctor'>;
}
declare module '@capacitor/cli/dist/android/open.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/android/open'>;
}
declare module '@capacitor/cli/dist/android/run.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/android/run'>;
}
declare module '@capacitor/cli/dist/android/update.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/android/update'>;
}
declare module '@capacitor/cli/dist/colors.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/colors'>;
}
declare module '@capacitor/cli/dist/common.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/common'>;
}
declare module '@capacitor/cli/dist/config.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/config'>;
}
declare module '@capacitor/cli/dist/cordova.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/cordova'>;
}
declare module '@capacitor/cli/dist/declarations.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/declarations'>;
}
declare module '@capacitor/cli/dist/definitions.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/definitions'>;
}
declare module '@capacitor/cli/dist/errors.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/errors'>;
}
declare module '@capacitor/cli/dist/framework-configs.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/framework-configs'>;
}
declare module '@capacitor/cli/dist/index' {
  declare module.exports: $Exports<'@capacitor/cli/dist'>;
}
declare module '@capacitor/cli/dist/index.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist'>;
}
declare module '@capacitor/cli/dist/ios/add.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/ios/add'>;
}
declare module '@capacitor/cli/dist/ios/build.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/ios/build'>;
}
declare module '@capacitor/cli/dist/ios/common.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/ios/common'>;
}
declare module '@capacitor/cli/dist/ios/doctor.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/ios/doctor'>;
}
declare module '@capacitor/cli/dist/ios/open.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/ios/open'>;
}
declare module '@capacitor/cli/dist/ios/run.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/ios/run'>;
}
declare module '@capacitor/cli/dist/ios/update.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/ios/update'>;
}
declare module '@capacitor/cli/dist/ipc.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/ipc'>;
}
declare module '@capacitor/cli/dist/log.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/log'>;
}
declare module '@capacitor/cli/dist/plugin.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/plugin'>;
}
declare module '@capacitor/cli/dist/sysconfig.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/sysconfig'>;
}
declare module '@capacitor/cli/dist/tasks/add.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/add'>;
}
declare module '@capacitor/cli/dist/tasks/build.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/build'>;
}
declare module '@capacitor/cli/dist/tasks/config.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/config'>;
}
declare module '@capacitor/cli/dist/tasks/copy.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/copy'>;
}
declare module '@capacitor/cli/dist/tasks/create.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/create'>;
}
declare module '@capacitor/cli/dist/tasks/doctor.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/doctor'>;
}
declare module '@capacitor/cli/dist/tasks/init.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/init'>;
}
declare module '@capacitor/cli/dist/tasks/list.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/list'>;
}
declare module '@capacitor/cli/dist/tasks/migrate.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/migrate'>;
}
declare module '@capacitor/cli/dist/tasks/new-plugin.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/new-plugin'>;
}
declare module '@capacitor/cli/dist/tasks/open.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/open'>;
}
declare module '@capacitor/cli/dist/tasks/run.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/run'>;
}
declare module '@capacitor/cli/dist/tasks/serve.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/serve'>;
}
declare module '@capacitor/cli/dist/tasks/sourcemaps.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/sourcemaps'>;
}
declare module '@capacitor/cli/dist/tasks/sync.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/sync'>;
}
declare module '@capacitor/cli/dist/tasks/telemetry.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/telemetry'>;
}
declare module '@capacitor/cli/dist/tasks/update.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/tasks/update'>;
}
declare module '@capacitor/cli/dist/telemetry.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/telemetry'>;
}
declare module '@capacitor/cli/dist/util/cli.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/cli'>;
}
declare module '@capacitor/cli/dist/util/emoji.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/emoji'>;
}
declare module '@capacitor/cli/dist/util/fn.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/fn'>;
}
declare module '@capacitor/cli/dist/util/fs.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/fs'>;
}
declare module '@capacitor/cli/dist/util/js.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/js'>;
}
declare module '@capacitor/cli/dist/util/monorepotools.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/monorepotools'>;
}
declare module '@capacitor/cli/dist/util/native-run.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/native-run'>;
}
declare module '@capacitor/cli/dist/util/node.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/node'>;
}
declare module '@capacitor/cli/dist/util/promise.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/promise'>;
}
declare module '@capacitor/cli/dist/util/subprocess.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/subprocess'>;
}
declare module '@capacitor/cli/dist/util/template.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/template'>;
}
declare module '@capacitor/cli/dist/util/term.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/term'>;
}
declare module '@capacitor/cli/dist/util/uuid.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/uuid'>;
}
declare module '@capacitor/cli/dist/util/xml.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/util/xml'>;
}
declare module '@capacitor/cli/dist/web/copy.js' {
  declare module.exports: $Exports<'@capacitor/cli/dist/web/copy'>;
}
