// flow-typed signature: 6984bde1b7c12651be4f2f73b47b52ed
// flow-typed version: <<STUB>>/@capacitor/core_v^5.3.0/flow_v0.216.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@capacitor/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@capacitor/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@capacitor/core/cordova' {
  declare module.exports: any;
}

declare module '@capacitor/core/dist/capacitor' {
  declare module.exports: any;
}

declare module '@capacitor/core/dist/index.cjs' {
  declare module.exports: any;
}

declare module '@capacitor/core/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@capacitor/core/cordova.js' {
  declare module.exports: $Exports<'@capacitor/core/cordova'>;
}
declare module '@capacitor/core/dist/capacitor.js' {
  declare module.exports: $Exports<'@capacitor/core/dist/capacitor'>;
}
declare module '@capacitor/core/dist/index.cjs.js' {
  declare module.exports: $Exports<'@capacitor/core/dist/index.cjs'>;
}
declare module '@capacitor/core/dist/index' {
  declare module.exports: $Exports<'@capacitor/core/dist'>;
}
declare module '@capacitor/core/dist/index.js' {
  declare module.exports: $Exports<'@capacitor/core/dist'>;
}
