apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kourier_app-backend
  template:
    metadata:
      labels:
        app: kourier_app-backend
    spec:
      containers:
      - name: backend-container
        image: your-registry/kourier_app-backend:latest
        ports:
        - containerPort: 80
