// flow-typed signature: ed10ca19d8a32e798589231db9e4bef7
// flow-typed version: <<STUB>>/react-multi-carousel_v^2.8.4/flow_v0.216.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-multi-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-multi-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-multi-carousel/dev/babel.config' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/dev/next.config' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/dev/postcss.config' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/Arrows' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/Carousel' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/CarouselItems' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/Dots' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/types' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/clones' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/common' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/dots' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/elementWidth' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/mouseOrTouchMove' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/next' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/previous' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/throttle' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/lib/utils/throwError' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/minify' {
  declare module.exports: any;
}

declare module 'react-multi-carousel/storybook-static/sb_dll/storybook_ui_dll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-multi-carousel/dev/babel.config.js' {
  declare module.exports: $Exports<'react-multi-carousel/dev/babel.config'>;
}
declare module 'react-multi-carousel/dev/next.config.js' {
  declare module.exports: $Exports<'react-multi-carousel/dev/next.config'>;
}
declare module 'react-multi-carousel/dev/postcss.config.js' {
  declare module.exports: $Exports<'react-multi-carousel/dev/postcss.config'>;
}
declare module 'react-multi-carousel/index' {
  declare module.exports: $Exports<'react-multi-carousel'>;
}
declare module 'react-multi-carousel/index.js' {
  declare module.exports: $Exports<'react-multi-carousel'>;
}
declare module 'react-multi-carousel/lib/Arrows.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/Arrows'>;
}
declare module 'react-multi-carousel/lib/Carousel.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/Carousel'>;
}
declare module 'react-multi-carousel/lib/CarouselItems.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/CarouselItems'>;
}
declare module 'react-multi-carousel/lib/Dots.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/Dots'>;
}
declare module 'react-multi-carousel/lib/index' {
  declare module.exports: $Exports<'react-multi-carousel/lib'>;
}
declare module 'react-multi-carousel/lib/index.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib'>;
}
declare module 'react-multi-carousel/lib/types.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/types'>;
}
declare module 'react-multi-carousel/lib/utils/clones.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/clones'>;
}
declare module 'react-multi-carousel/lib/utils/common.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/common'>;
}
declare module 'react-multi-carousel/lib/utils/dots.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/dots'>;
}
declare module 'react-multi-carousel/lib/utils/elementWidth.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/elementWidth'>;
}
declare module 'react-multi-carousel/lib/utils/index' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils'>;
}
declare module 'react-multi-carousel/lib/utils/index.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils'>;
}
declare module 'react-multi-carousel/lib/utils/mouseOrTouchMove.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/mouseOrTouchMove'>;
}
declare module 'react-multi-carousel/lib/utils/next.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/next'>;
}
declare module 'react-multi-carousel/lib/utils/previous.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/previous'>;
}
declare module 'react-multi-carousel/lib/utils/throttle.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/throttle'>;
}
declare module 'react-multi-carousel/lib/utils/throwError.js' {
  declare module.exports: $Exports<'react-multi-carousel/lib/utils/throwError'>;
}
declare module 'react-multi-carousel/minify.js' {
  declare module.exports: $Exports<'react-multi-carousel/minify'>;
}
declare module 'react-multi-carousel/storybook-static/sb_dll/storybook_ui_dll.js' {
  declare module.exports: $Exports<'react-multi-carousel/storybook-static/sb_dll/storybook_ui_dll'>;
}
